export default {
  CALCULATION_SET_METHOD: 'CALCULATION_SET_METHOD',
  CALCULATION_SET_NORMALIZATION: 'CALCULATION_SET_NORMALIZATION',
  CALCULATION_SET_WEIGHTS_VALUE: 'CALCULATION_SET_WEIGHTS_VALUE',
  CALCULATION_SET_WEIGHTS_TYPE: 'CALCULATION_SET_WEIGHTS_TYPE',
  CALCULATION_SET_WEIGHTS_METHOD: 'CALCULATION_SET_WEIGHTS_METHOD',
  CALCULATION_SET_ALTERNATIVES: 'CALCULATION_SET_ALTERNATIVES',
  CALCULATION_SET_CRITERIA: 'CALCULATION_SET_CRITERIA',
  CALCULATION_SET_MATRIX: 'CALCULATION_SET_MATRIX',
  CALCULATION_SET_MATRIX_FILE: 'CALCULATION_SET_MATRIX_FILE',
  CALCULATION_SET_PREFERENCE_FUNCTION: 'CALCULATION_SET_PREFERENCE_FUNCTION',
  CALCULATION_CHECK_FORM: 'CALCULATION_CHECK_FORM',
  CALCULATION_RESET_FORM: 'CALCULATION_RESET_FORM',

  GET_RESULTS: 'GET_RESULTS',
  GET_RESULTS_START: 'GET_RESULTS_START',
  GET_RESULTS_SUCCESS: 'GET_RESULTS_SUCCESS',
  GET_RESULTS_FAIL: 'GET_RESULTS_FAIL',

  SET_CORRELATIONS_METHOD: 'SET_CORRELATIONS_METHOD',
  CORRELATIONS_ADD_ELEMENTS: 'CORRELATIONS_ADD_ELEMENTS',
  CORRELATIONS_REMOVE_ELEMENTS: 'CORRELATIONS_REMOVE_ELEMENTS',
  CORRELATIONS_RESET_ELEMENTS: 'CORRELATIONS_RESET_ELEMENTS',

  GET_CORRELATIONS: 'GET_CORRELATIONS',
  GET_CORRELATIONS_START: 'GET_CORRELATIONS_START',
  GET_CORRELATIONS_SUCCESS: 'GET_CORRELATIONS_SUCCESS',
  GET_CORRELATIONS_FAIL: 'GET_CORRELATIONS_FAIL',
}