export default {
  CALCULATION_SET_METHOD: 'CALCULATION_SET_METHOD',
  CALCULATION_SET_NORMALIZATION: 'CALCULATION_SET_NORMALIZATION',
  CALCULATION_SET_WEIGHTS_VALUE: 'CALCULATION_SET_WEIGHTS_VALUE',
  CALCULATION_SET_WEIGHTS_TYPE: 'CALCULATION_SET_WEIGHTS_TYPE',
  CALCULATION_SET_WEIGHTS_METHOD: 'CALCULATION_SET_WEIGHTS_METHOD',
  CALCULATION_SET_ALTERNATIVES: 'CALCULATION_SET_ALTERNATIVES',
  CALCULATION_SET_CRITERIA: 'CALCULATION_SET_CRITERIA',
  CALCULATION_SET_MATRIX: 'CALCULATION_SET_MATRIX',
  CALCULATION_SET_MATRIX_FILE: 'CALCULATION_SET_MATRIX_FILE',
  CALCULATION_SET_PREFERENCE_FUNCTION: 'CALCULATION_SET_PREFERENCE_FUNCTION',
  CALCULATION_CHECK_FORM: 'CALCULATION_CHECK_FORM',
  CALCULATION_RESET_FORM: 'CALCULATION_RESET_FORM',

  CALCULATION_RESULTS: 'CALCULATION_RESULTS',
  CALCULATION_RESULTS_START: 'CALCULATION_RESULTS_START',
  CALCULATION_RESULTS_SUCCESS: 'CALCULATION_RESULTS_SUCCESS',
  CALCULATION_RESULTS_FAIL: 'CALCULATION_RESULTS_FAIL'
}