export default {
  CALCULATION_SET_METHOD: 'CALCULATION_SET_METHOD',
  CALCULATION_SET_NORMALIZATION: 'CALCULATION_SET_NORMALIZATION',
  CALCULATION_SET_WEIGHTS_VALUE: 'CALCULATION_SET_WEIGHTS_VALUE',
  CALCULATION_SET_WEIGHTS_TYPE: 'CALCULATION_SET_WEIGHTS_TYPE',
  CALCULATION_SET_WEIGHTS_METHOD: 'CALCULATION_SET_WEIGHTS_METHOD',
  CALCULATION_SET_ALTERNATIVES: 'CALCULATION_SET_ALTERNATIVES',
  CALCULATION_SET_CRITERIA: 'CALCULATION_SET_CRITERIA',
  CALCULATION_SET_MATRIX: 'CALCULATION_SET_MATRIX',
  CALCULATION_SET_MATRIX_FILE: 'CALCULATION_SET_MATRIX_FILE',
  CALCULATION_SET_PREFERENCE_FUNCTION: 'CALCULATION_SET_PREFERENCE_FUNCTION',
  CALCULATION_CHECK_FORM: 'CALCULATION_CHECK_FORM',
  CALCULATION_RESET_FORM: 'CALCULATION_RESET_FORM',

  CALCULATION_RESULTS: 'CALCULATION_RESULTS',
  CALCULATION_RESULTS_START: 'CALCULATION_RESULTS_START',
  CALCULATION_RESULTS_SUCCESS: 'CALCULATION_RESULTS_SUCCESS',
  CALCULATION_RESULTS_FAIL: 'CALCULATION_RESULTS_FAIL',

  CALCULATION_SET_CORRELATIONS_METHOD: 'CALCULATION_SET_CORRELATIONS_METHOD',
  CALCULATION_ADD_ELEMENTS: 'CALCULATION_ADD_ELEMENTS',
  CALCULATION_REMOVE_ELEMENTS: 'CALCULATION_REMOVE_ELEMENTS',
  CALCULATION_RESET_CORRELATIONS: 'CALCULATION_RESET_CORRELATIONS',

  CALCULATION_CORRELATIONS: 'CALCULATION_CORRELATIONS',
  CALCULATION_CORRELATIONS_START: 'CALCULATION_CORRELATIONS_START',
  CALCULATION_CORRELATIONS_SUCCESS: 'CALCULATION_CORRELATIONS_SUCCESS',
  CALCULATION_CORRELATIONS_FAIL: 'CALCULATION_CORRELATIONS_FAIL',
}